on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      ftp:
        image: stilliard/pure-ftpd
        ports:
          - 21:21
          - 30000-30009:30000-30009
        env:
          FTP_USER_NAME: bob
          FTP_USER_PASS: 12345
          FTP_USER_HOME: /home/bob
      sftp:
        image: atmoz/sftp
        ports:
         - 2222:22
        volumes:
          - /sftp-users.conf:/etc/sftp-users.conf:ro
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - run: |
          sudo apt-get install nmap
      - run: |
          nmap -sT localhost
          ifconfig
